#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("projet_chat.Resource", IsApplication=true)]

namespace projet_chat
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Image1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Image2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Image3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Image4 = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050015
			public const int btnAbonner = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int btnAddMessage = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int btnCreat = 2131034134;
			
			// aapt resource value: 0x7f050003
			public const int btnEnvoyerMessageDialog = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int btnExit = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int btnSortirMessageDialog = 2131034116;
			
			// aapt resource value: 0x7f050012
			public const int btnValiderConnexion = 2131034130;
			
			// aapt resource value: 0x7f050006
			public const int btnValiderCreatSujet = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int gridLayout1 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int imgUser = 2131034121;
			
			// aapt resource value: 0x7f050014
			public const int lstMessage = 2131034132;
			
			// aapt resource value: 0x7f050017
			public const int lstSujet = 2131034135;
			
			// aapt resource value: 0x7f050001
			public const int lstSujetsAbon = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050010
			public const int textView2 = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int txtLogin = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int txtMessageDialog = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int txtNbMessageItem = 2131034125;
			
			// aapt resource value: 0x7f050005
			public const int txtNomSujet = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int txtNomSujetItem = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int txtNomUserItem = 2131034123;
			
			// aapt resource value: 0x7f050011
			public const int txtPassword = 2131034129;
			
			// aapt resource value: 0x7f05000a
			public const int txtPrenomUserItem = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int txtTextMessageItemM = 2131034126;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AbonnementLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int createMessageDialogLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int createSujetDialogLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ItemAbonnement = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ItemMessage = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ItemSujet = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MessageLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SujetLayout = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
